version: '3.8'
services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - thread-net

  #spring-boot-app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #    target: builder
  #  container_name: spring-boot-app
  #  command: ["gradle", "bootRun"]
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - postgres
  #  environment:
  #    DB_URL: jdbc:postgresql://postgres:5432/thread
  #    DB_USER: postgres
  #    DB_PASSWORD: postgres
  #  volumes:
  #    - ./src:/app/src
  #  networks:
  #    - thread-net

networks:
  thread-net:
